# Generated by Django 2.0.7 on 2018-10-24 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bovino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_animal', models.CharField(max_length=50)),
                ('numeracao_do_animal', models.IntegerField(unique=True)),
                ('peso_do_animal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('anos', models.IntegerField()),
                ('meses', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Bovinos',
            },
        ),
        migrations.CreateModel(
            name='Equino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_animal', models.CharField(max_length=50)),
                ('numeracao_do_animal', models.IntegerField(unique=True)),
                ('peso_do_animal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('anos', models.IntegerField()),
                ('meses', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Equinos',
            },
        ),
        migrations.CreateModel(
            name='MedidaBovino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_medida', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='imagens_medidas')),
                ('medida_obtida', models.DecimalField(decimal_places=2, max_digits=5)),
                ('local_ferida', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('animal_da_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bovino')),
            ],
            options={
                'verbose_name_plural': 'Medida Bovinos',
            },
        ),
        migrations.CreateModel(
            name='MedidaEquino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_medida', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='imagens_medidas')),
                ('medida_obtida', models.DecimalField(decimal_places=2, max_digits=5)),
                ('local_ferida', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('animal_da_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Equino')),
            ],
            options={
                'verbose_name_plural': 'Medida Equinos',
            },
        ),
        migrations.CreateModel(
            name='RacaBovino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_raca', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Raças Bovinos',
            },
        ),
        migrations.CreateModel(
            name='RacaEquino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_raca', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Raças Equinos',
            },
        ),
        migrations.CreateModel(
            name='SexoAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('F', 'Fêmea'), ('M', 'Macho')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Sexo',
            },
        ),
        migrations.CreateModel(
            name='TipoFerida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acidental', 'acidental'), ('induzida', 'induzida')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Tipo da ferida',
            },
        ),
        migrations.AddField(
            model_name='medidaequino',
            name='tipo_ferida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.TipoFerida'),
        ),
        migrations.AddField(
            model_name='medidabovino',
            name='tipo_ferida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.TipoFerida'),
        ),
        migrations.AddField(
            model_name='equino',
            name='raca_do_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.RacaEquino'),
        ),
        migrations.AddField(
            model_name='equino',
            name='sexo_do_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.SexoAnimal'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='raca_do_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.RacaBovino'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='sexo_do_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.SexoAnimal'),
        ),
    ]
