# Generated by Django 2.0.7 on 2018-11-21 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_animal', models.CharField(max_length=50)),
                ('numeracao_do_animal', models.IntegerField(unique=True)),
                ('peso_do_animal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('anos', models.IntegerField()),
                ('meses', models.IntegerField()),
                ('raca', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Animais',
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Espécies',
            },
        ),
        migrations.CreateModel(
            name='MedidaAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_medida', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='imagens_medidas')),
                ('medida_obtida', models.DecimalField(decimal_places=2, max_digits=5)),
                ('local_ferida', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('animal_da_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Animal')),
            ],
            options={
                'verbose_name_plural': 'Medidas',
            },
        ),
        migrations.CreateModel(
            name='SexoAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Sexo',
            },
        ),
        migrations.CreateModel(
            name='TipoFerida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acidental', 'acidental'), ('induzida', 'induzida')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Tipo da ferida',
            },
        ),
        migrations.AddField(
            model_name='medidaanimal',
            name='tipo_ferida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.TipoFerida'),
        ),
        migrations.AddField(
            model_name='animal',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Especie'),
        ),
        migrations.AddField(
            model_name='animal',
            name='sexo_do_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.SexoAnimal'),
        ),
    ]
