# Generated by Django 2.0.7 on 2018-07-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=50)),
                ('ultimo_nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('data_nasc', models.DateField()),
                ('senha', models.CharField(max_length=16)),
            ],
        ),
    ]
