# Generated by Django 2.0.7 on 2018-07-11 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='data_nasc',
        ),
    ]
