# Generated by Django 2.0.7 on 2018-08-04 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_userprofile_data_nasc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_animal', models.CharField(max_length=50)),
                ('numeracao_animal', models.IntegerField(unique=True)),
                ('peso_animal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('idade_animal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MedidaImagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_medida', models.DateField()),
                ('medida_obtida', models.DecimalField(decimal_places=2, max_digits=5)),
                ('animal_da_medida', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='RacaAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_raca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SexoAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('F', 'Fêmea'), ('M', 'Macho')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='raca_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.RacaAnimal'),
        ),
        migrations.AddField(
            model_name='animal',
            name='sexo_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.SexoAnimal'),
        ),
    ]
