# Generated by Django 2.0.7 on 2018-08-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180803_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidaimagem',
            name='codigo_medida',
            field=models.CharField(default='', max_length=50),
        ),
    ]
