# Generated by Django 2.0.7 on 2018-08-04 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_medidaimagem_codigo_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidaimagem',
            name='animal_da_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Animal'),
        ),
    ]
