# Generated by Django 2.0.7 on 2018-08-04 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180803_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name_plural': 'Animais'},
        ),
        migrations.AlterModelOptions(
            name='medidaimagem',
            options={'verbose_name_plural': 'Medida Imagens'},
        ),
        migrations.AlterModelOptions(
            name='racaanimal',
            options={'verbose_name_plural': 'Raças'},
        ),
        migrations.AlterModelOptions(
            name='sexoanimal',
            options={'verbose_name_plural': 'Sexo'},
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
