# Generated by Django 2.0.7 on 2018-08-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180804_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidaimagem',
            name='image',
            field=models.ImageField(blank=True, upload_to='imagens_medidas'),
        ),
    ]
